name: Tests
on: [push]
jobs:
  Ubuntu-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libpcap
        run: sudo apt-get install -y libpcap-dev

      - name: Initialize submodules
        run: git submodule init && git submodule update

      - name: Initialize build system
        run: mkdir build && cd build && cmake ..

      - name: Build tests
        run: cmake --build build --target tests

      - name: Run tests
        run: ctest build
