name: Tests
on: [push]
jobs:
  Ubuntu-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git submodule init
      - run: mkdir build
      - run: cd build && cmake ..
      - run: cmake --build build --target tests
      - run: ctest build
